spring.application.name=guestBook
spring.jpa.database=postgresql
spring.datasource.username=gb
spring.datasource.password=1234
spring.datasource.name=
spring.datasource.url=jdbc:postgresql://localhost:5432/guest_book
